### ISSUE TITLE
Spark with Scala 2.11?

### ISSUE THREAD

**Issue by junshi15** [BIDData/BIDMach_Spark#2]
For this to work, do I need Spark with Scala 2.11 support? The available spark binaries are built with scala 2.10 at this moment. 
http://spark.apache.org/downloads.html

**Comment by LinZhiyuan** [comment]
You can follow this link to build Spark with Scala 2.11. 
http://spark.apache.org/docs/latest/building-spark.html#building-for-scala-211

**Comment by junshi15** [comment]
Thanks, I have built it per instructions.
