### ISSUE TITLE
Incompatibilities / versioning issues wrt BIDMat?

### ISSUE THREAD

**Issue by javadba** [BIDData/BIDMach_Spark#5]
The compilation errors below refer to code that is not checked in (and never has been)  to BIDMat

> package
> [warn] Credentials file /Users/steve/.ivy2/.credentials does not exist
> [info] Compiling 3 Scala sources to /git/BIDMach_Spark/target/scala-2.11/classes...
> [error] /git/BIDMach_Spark/src/main/scala/BIDMach/RunOnSpark.scala:107: value combineModels is not a member of BIDMach.models.Model
> [error]     l.model.combineModels(ipass, r.model)
> [error]             ^
> [error] /git/BIDMach_Spark/src/main/scala/BIDMach/RunOnSpark.scala:116: value updateM is not a member of BIDMach.Learner
> [error]     reduced_learner.updateM(0)
> [error]                     ^
> [error] /git/BIDMach_Spark/src/main/scala/BIDMach/RunOnSpark.scala:130: value updateM is not a member of BIDMach.Learner
> [error]       reduced_learner.updateM(i)
> [error]                       ^
> [error] three errors found
> [error](compile:compile) Compilation failed
> [error] Total time: 1 s, completed May 11, 2016 9:25:53 AM

**Comment by javadba** [comment]
Environment:  
        os/x 10.11
        scala 2.11.2
        java 1.8  

The BIDMat and BIDMach jars from latest git versions as of 5/13/16 15:40 PST were already copied to the BIDMach_Spark libs dir:

$ll lib
total 17768
-rw-r--r--   1 steve  staff  1141129 May 11 09:03 sbt-launch.jar
-rw-r--r--   1 steve  staff  2158785 May 11 09:14 BIDMat.jar
drwxr-xr-x   5 steve  staff      170 May 11 09:25 .
-rw-r--r--   1 steve  staff  5789951 May 12 12:57 BIDMach.jar
drwxr-xr-x  17 steve  staff      578 May 12 19:28 ..

**Comment by jcanny** [comment]
OK, combineModels has been added to BIDMach and compiling works now. You'll also need to copy the jcuda jars and apache commons math jar (commons-math-*.jar) from BIDMach/lib to BIDMach_Spark/lib

**Comment by javadba** [comment]
Thx John! Will take look l8r today.

**Comment by javadba** [comment]
Working!

What I tested:  creating a basic BIDMat matrix and saving to hdfs: 

$bidmath
Loading /git/BIDMat/lib/bidmat_init.scala...
..
scala> val a = rand(3000,3000)

scala> saveFMat("hdfs://localhost:8020/myf.fmat",a)
16/06/10 14:47:29 INFO compress.CodecPool: Got brand-new compressor [.deflate]

$ hadoop dfs -ls /myf.fmat

-rw-r--r--   1 macuser supergroup   32323012 2016-06-10 14:47 /myf.fmat

Will look into further testing.
